spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: test1234
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
  
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true 
        trace: false
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  
  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}
      timeout: 5000ms
      connect-timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

logging:
  level:
    com.hyundai.autoever.security.assignment: INFO
    org.springframework.security: INFO
    org.springframework.data.redis: INFO
    io.lettuce.core: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: 8080

kakao:
  api:
    url: ${KAKAO_API_URL:http://localhost:8081}
    username: autoever
    password: 1234
    test:
      enabled: true
      failure-rate: 10

sms:
  api:
    url: ${SMS_API_URL:http://localhost:8082}
    username: autoever
    password: 5678

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always 