spring:
  # 데이터베이스 설정 (H2 인메모리)
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  
  # Redis 설정 - 더 구체적인 설정 추가
  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}
      timeout: 5000ms
      connect-timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

# 로깅 설정
logging:
  level:
    com.hyundai.autoever.security.assignment: INFO
    org.springframework.security: INFO
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 서버 설정
server:
  port: 8080

# Mock API 설정
kakao:
  api:
    url: ${KAKAO_API_URL:http://localhost:8081}
    username: autoever
    password: 1234

sms:
  api:
    url: ${SMS_API_URL:http://localhost:8082}
    username: autoever
    password: 5678

# Actuator 설정 (헬스체크용)
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always 